import React from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function TermsPage() {
  return (
    <>
      <main className="min-h-screen pb-24 relative overflow-hidden bg-[#faf9f6]">
        <Navbar />
        
        <section className="pt-32 pb-16 px-6 max-w-4xl mx-auto relative z-10">
          <div className="mb-12">
            <h1 className="font-serif font-bold text-5xl md:text-6xl mb-6 tracking-tight text-brand-1">Terms of Service</h1>
            <p className="font-sans text-lg text-foreground/60">Last Updated: June 2026</p>
          </div>

          <div className="prose prose-lg prose-headings:font-serif prose-headings:text-brand-1 prose-a:text-brand-4 hover:prose-a:text-brand-3 max-w-none text-foreground/80 font-sans leading-relaxed">
            <p>
              Welcome to Notrik! These Terms of Service ("Terms") govern your use of the Notrik website, app, and AI study engine services (collectively, the "Service") provided by Notrik Technologies ("we", "us", or "our").
            </p>

            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you do not have permission to access the Service.
            </p>

            <h2>2. Subscriptions and Payments</h2>
            <ul>
              <li><strong>Billing:</strong> You will be billed in advance on a recurring and periodic basis (such as monthly or annually), depending on the type of subscription plan you select.</li>
              <li><strong>UPI and Cards:</strong> We support payments via Razorpay. All transactions are securely processed.</li>
              <li><strong>Cancellations:</strong> You may cancel your subscription at any time. Your cancellation will take effect at the end of the current paid term. No questions asked.</li>
              <li><strong>Fair Use Policy:</strong> To ensure optimal performance and prevent abuse or scraping, plans with unmetered or 'Unlimited' features are subject to a soft-limit Fair Use Policy. For instance, the Unlimited Plan includes up to 150 high-fidelity note/flashcard transformations per month, and AI Mentor chat message limits are dynamically adjusted based on server load. Study accounts exceeding these reasonable thresholds will be temporarily throttled or reviewed by support.</li>
            </ul>

            <h2>3. Acceptable Use Policy</h2>
            <p>
              Our Service is intended for personal, educational, and academic use. You agree not to:
            </p>
            <ul>
              <li>Upload malicious code, explicit content, or content you do not have the right to process.</li>
              <li>Attempt to reverse-engineer our proprietary AI extraction engine.</li>
              <li>Share premium account access across multiple users (except where explicitly allowed by your tier).</li>
            </ul>

            <h2>4. Intellectual Property</h2>
            <p>
              The original study materials you upload remain your property. However, the software, algorithms, designs, and branding of Notrik are the exclusive property of Notrik Technologies.
            </p>

            <h2>5. Disclaimer of Warranties</h2>
            <p>
              While our AI engine is highly accurate for competitive exams (JEE/NEET/UPSC), the Service is provided "AS IS" and "AS AVAILABLE" without warranty of any kind. You should always verify critical study material generated by AI.
            </p>

            <h2>6. Limitation of Liability</h2>
            <p>
              In no event shall Notrik Technologies be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
            </p>
          </div>
        </section>

        <Footer />
      </main>
    </>
  );
}
